# Generated by Django 5.1.7 on 2025-03-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
