# Generated by Django 5.1.7 on 2025-04-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_interests_alter_customuser_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.IntegerField()),
                ('to_user', models.IntegerField()),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
