# Generated by Django 5.1.7 on 2025-04-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
