# Generated by Django 5.1.7 on 2025-04-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.IntegerField()),
                ('to_user', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
