# Generated by Django 5.1.7 on 2025-04-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_friendstatus_delete_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendstatus',
            name='to_user',
        ),
        migrations.AddField(
            model_name='friendstatus',
            name='user_a',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendstatus',
            name='user_b',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
