databases:
     - name: myp_db
       databaseName: myp_db
       user: myp_db_user

   services:
     - type: web
       name: myp-backend
       runtime: python
       buildCommand: pip install -r requirements.txt
       startCommand: gunicorn myp.wsgi:application
       envVars:
         - key: DATABASE_URL
           fromDatabase:
             name: myp_db
             property: connectionString
         - key: SECRET_KEY
           generateValue: true
         - key: DJANGO_DEBUG
           value: true
